<div style="width: 600px; margin: 0 auto; background-color: #002d75; background-image: url('https://ambiparlogtech.com/flex/wp-content/uploads/2024/01/ambipar-cargo-footer-background.png'); background-size: contain; background-repeat: no-repeat; background-position: center bottom; padding: 20px;font-family: Arial, sans-serif;"><img alt="SouNet" src="https://ambiparlogtech.com/wp-content/uploads/2023/02/ambipar_white_2023.png" width="250px" />
	<h1 style="text-align: center; color:#fff;"><span style="font-size:22px;">Bem-vindo à Ambipar Logtech! Aanote em sua agenda nosso Webinar. 😀</span></h1>
	
	<div style="background-color: #00000075; padding: 10px;">
	<p dir="ltr" style="line-height:1.3800000000000001;margin-top:15pt;margin-bottom:15pt;"><strong><span style="font-size:20px;"><span id="docs-internal-guid-9d10c87c-7fff-5653-d6e2-facae740ddff"><span style="font-family: Arial, sans-serif; color: #f6f6f6; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">Olá, [NOME DO LEAD]!</span></span></span></strong></p>
	
	<p dir="ltr" style="line-height:1.3800000000000001;margin-top:15pt;margin-bottom:15pt;"><span id="docs-internal-guid-9d10c87c-7fff-5653-d6e2-facae740ddff"><span style="font-size: 12pt; font-family: Arial, sans-serif; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; color: #f6f6f6; vertical-align: baseline; white-space-collapse: preserve;">É com grande satisfação que a equipe da Ambipar Logtech dá as boas-vindas a você e expressa nossa alegria pelo seu interesse em participar do nosso Webinar. Esteja atento(a) aos nossos e-mails para mais informações e atualizações.<br><br>Agradecemos imensamente pela oportunidade de nos conectarmos com você e pela sua disposição em explorar o universo da logística de frota com a Ambipar Logtech.<br><br>Não se esqueça de marcar em sua agenda: nosso Webinar está marcado para o dia 22/02/2024. Logo compartilharemos o link por e-mail para acesso.<br><br>Nós, da Ambipar Logtech, estamos empenhados em oferecer soluções inovadoras e eficientes para otimizar a gestão de frota de transportadoras. Sabemos que a logística é um elemento crucial para o sucesso de qualquer operação de transporte, e estamos aqui para ajudar a tornar esse processo mais inteligente, seguro e sustentável.<br><br>Por favor, não hesite em entrar em contato conosco caso tenha alguma dúvida ou precise de mais informações sobre nossos serviços e soluções para logística de frota.
    </span>

	</div>
	&nbsp;
	
	<div style="text-align: center;"><span class="msohide es-button-border-2 es-button-border" style="border-style:solid;border: none;background:#ecdfc3;border-width:2px;display:inline-block;border-radius:5px;width:fit-content;mso-hide:all"><a class="es-button es-button-1" href="https://api.whatsapp.com/send/?phone=5519999758365&text=Olá%21+Tenho+interesse+em+ser+um+franqueado+Fichips&type=phone_number&app_absent=0" style="mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#fff;font-size:18px;border-style:solid;border-color:#ecdfc3;border-width:10px;display:inline-block;background:#ecdfc3;border-radius:10px;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-weight:bold; color: #2c2c2c; font-style:normal;line-height:22px;width:auto;text-align:center" target="_blank">QUERO CONHECER O MODELO STREET PUB</a></span></div>
	&nbsp;<br style="color: rgb(255, 255, 255); font-family: Arial, sans-serif;" />
	<span style="color: rgb(255, 255, 255); font-family: Arial, sans-serif;">Ambipar Logtech</span><br style="color: rgb(255, 255, 255); font-family: Arial, sans-serif;" />
	<span style="color: rgb(255, 255, 255); font-family: Arial, sans-serif;">Com Mireli Bueno</span><br />
	&nbsp;
	<div style="background-color: #D3FE00; border: 1px solid #D3FE00; color: #000000; text-align: center; padding: 10px;">
	<p style="font-size: 10px;">Voc&ecirc; est&aacute; recebendo este e-mail porque visitou nosso site.<br />
	Certifique-se de que nossas mensagens cheguem &agrave; sua caixa de entrada (e n&atilde;o &agrave;s suas pastas em massa ou lixo eletr&ocirc;nico).</p>
	<a href="https://ambipar.com/politicas/Politica-de-Privacidade-e-Protecao-de-Dados-Pessoais" style="font-size:8px; color: #fff;">TERMOS DE USO E POL&Iacute;TICA DE PRIVACIDADE</a> | <a href="https://ambiparlogtech.com/" style="font-size:8px; color: #fff;">POLITICA DE CANCELAMENTO</a></div>
	</div>
	